### ISSUE TITLE
[ADD] J'ai oublié un truc

### ISSUE THREAD

**Issue by ghost** [DamienBouvet22/Presentation-BDD#2]
Rebonjour Mr Bouvet.

J'ai oublié de mentionner un truc dans ma dernière issue. 
J'adorerai avoir un schéma en 3 dimensions pour mieux comprendre les fondements des BDD.

Bien cordialement,
Folliguet Valentin.

**Comment by DamienBouvet22** [comment]
Bonjour Mr Folliguet,

J'ai bien pris en compte vos requêtes, merci infiniment pour leur
pertinence.
Nous nous y mettons dès à présent et espérons pouvoir passer à la V2 très
prochainement.
Merci de votre participation au travers ces idées de Génie et de votre
patience le temps de la réalisation.

Cordialement

Le lun. 20 janv. 2020 à 13:51, ValentinFLGT <notifications@github.com> a
écrit :

**Comment by DamienBouvet22** [comment]
C'est tout bon mon cher monsieur!!!
